DROP TABLE IF EXISTS prescription_items CASCADE;
DROP TABLE IF EXISTS prescriptions CASCADE;
DROP TABLE IF EXISTS lab_results CASCADE;
DROP TABLE IF EXISTS diagnoses CASCADE;
DROP TABLE IF EXISTS vital_signs CASCADE;
DROP TABLE IF EXISTS clinical_evaluations CASCADE;
DROP TABLE IF EXISTS encounters CASCADE;

DROP TYPE IF EXISTS prescription_item_status CASCADE;
DROP TYPE IF EXISTS prescription_frequency CASCADE;
DROP TYPE IF EXISTS prescription_route CASCADE;
DROP TYPE IF EXISTS lab_flag CASCADE;
DROP TYPE IF EXISTS lab_category CASCADE;
DROP TYPE IF EXISTS diagnosis_type CASCADE;
DROP TYPE IF EXISTS vital_source CASCADE;
DROP TYPE IF EXISTS encounter_status CASCADE;
